import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../../constants/colors";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },

  header: {
    backgroundColor: COLORS.BLUE,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "android" ? 0 : 8,
    paddingBottom: 14,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#fff",
  },
  headerSub: {
    marginTop: 4,
    fontSize: 13,
    color: "#E5ECFF",
  },

  listPad: {
    padding: 16,
    paddingBottom: 20,
  },

  chatPrivacyCard: {
    marginBottom: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DDE6F4",
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  chatPrivacyIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
  },
  chatPrivacyBody: {
    flex: 1,
  },
  chatPrivacyTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  chatPrivacyText: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 17,
    color: "#64748B",
  },

  termsGateWrap: {
    padding: 16,
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
  },
  termsGateScroll: {
    flex: 1,
  },
  termsGateScrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingVertical: 16,
  },

  roomCard: {
    backgroundColor: "#fff",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 12,
    marginBottom: 12,
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  swipeRoomWrap: {
    position: "relative",
    marginBottom: 12,
    overflow: "hidden",
    borderRadius: 14,
  },
  roomSwipeCard: {
    backgroundColor: "#F8FAFC",
    borderRadius: 14,
  },
  roomCardSwipe: {
    marginBottom: 0,
  },
  roomDeleteAction: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "flex-start",
    justifyContent: "center",
    backgroundColor: "#FEE2E2",
    borderRadius: 14,
  },
  roomDeleteBtn: {
    width: 76,
    height: "100%",
    backgroundColor: "#DC2626",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
  },
  roomDeleteBtnDisabled: {
    opacity: 0.72,
  },
  roomDeleteText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#fff",
  },
  roomAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#E5E7EB",
  },
  roomAvatarFallback: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#EAF1FF",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.BLUE,
  },
  roomBody: {
    flex: 1,
  },
  roomTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  roomName: {
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
    color: "#111827",
  },
  roomTime: {
    fontSize: 11,
    color: "#6B7280",
    fontWeight: "600",
  },
  roomSub: {
    marginTop: 4,
    fontSize: 12,
    color: "#6B7280",
  },
  roomLastMsg: {
    marginTop: 6,
    fontSize: 13,
    color: "#374151",
    fontWeight: "500",
  },
  roomLastMsgHidden: {
    color: "#9A3412",
    fontStyle: "italic",
  },
  roomPreviewRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  unreadBadge: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    paddingHorizontal: 6,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
  },
  unreadBadgeText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#fff",
  },

  centerState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    gap: 10,
  },
  stateText: {
    fontSize: 14,
    color: "#4B5563",
    textAlign: "center",
  },
  demoActionBtn: {
    marginTop: 12,
    backgroundColor: COLORS.BLUE,
    paddingHorizontal: 16,
    height: 42,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  demoActionText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },

  reviewOutlineBtn: {
    paddingHorizontal: 16,
    height: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#EFF6FF",
    alignItems: "center",
    justifyContent: "center",
  },
  reviewOutlineBtnText: {
    color: COLORS.BLUE,
    fontSize: 14,
    fontWeight: "700",
  },

  roomHeader: {
    backgroundColor: COLORS.BLUE,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "android" ? 0 : 10,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  roomHeaderBody: {
    flex: 1,
  },
  roomHeaderTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: "#fff",
  },
  roomHeaderSub: {
    marginTop: 2,
    fontSize: 12,
    color: "#E5ECFF",
  },
  chatHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  headerIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#E5E7EB",
  },
  headerAvatarFallback: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerAvatarInitials: {
    fontSize: 12,
    fontWeight: "800",
    color: "#fff",
  },
  chatModeRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  chatModeBtn: {
    flex: 1,
    height: 42,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#BFDBFE",
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  chatModeBtnActive: {
    borderColor: COLORS.BLUE,
    backgroundColor: COLORS.BLUE,
  },
  chatModeText: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.BLUE,
  },
  chatModeTextActive: {
    color: "#fff",
  },

  msgListPad: {
    paddingHorizontal: 12,
    paddingVertical: 16,
    gap: 10,
  },

  msgRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  msgRowMine: {
    justifyContent: "flex-end",
  },
  msgRowOther: {
    justifyContent: "flex-start",
  },

  msgAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#E5E7EB",
  },
  msgAvatarFallback: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "#EAF1FF",
    alignItems: "center",
    justifyContent: "center",
  },
  msgAvatarInitials: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.BLUE,
  },

  msgBubbleWrap: {
    maxWidth: "78%",
  },
  msgSenderName: {
    marginBottom: 4,
    marginLeft: 2,
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "700",
  },
  msgBubble: {
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  msgBubbleMine: {
    backgroundColor: COLORS.BLUE,
    borderBottomRightRadius: 6,
  },
  msgBubbleOther: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderBottomLeftRadius: 6,
  },
  msgText: {
    fontSize: 14,
    color: "#111827",
    lineHeight: 20,
  },
  msgTextMine: {
    color: "#fff",
  },
  msgMetaRow: {
    marginTop: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 4,
  },
  msgTime: {
    fontSize: 11,
    color: "#6B7280",
  },
  msgDelete: {
    fontSize: 11,
    color: "#DC2626",
    fontWeight: "700",
  },
  msgHint: {
    fontSize: 10,
    color: "#94A3B8",
    fontWeight: "600",
  },
  msgActionBtn: {
    minWidth: 104,
    height: 24,
    borderRadius: 8,
    paddingHorizontal: 8,
    flexDirection: "row",
    gap: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8EEF8",
  },
  msgActionText: {
    fontSize: 11,
    color: COLORS.BLUE,
    fontWeight: "700",
  },
  msgMaskedBubble: {
    borderStyle: "dashed",
    backgroundColor: "#FFF7ED",
    borderColor: "#FDBA74",
  },
  msgMaskedText: {
    color: "#9A3412",
    fontStyle: "italic",
  },
  msgRecalledBubble: {
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  msgRecalledText: {
    color: "#64748B",
    fontStyle: "italic",
  },

  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  searchBox: {
    flex: 1,
    height: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#DDE6F4",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: "#111827",
    paddingVertical: 0,
  },
  searchBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: COLORS.BLUE,
    alignItems: "center",
    justifyContent: "center",
  },

  blockBanner: {
    marginHorizontal: 12,
    marginTop: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FED7AA",
    backgroundColor: "#FFF7ED",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  blockBannerText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 17,
    color: "#9A3412",
    fontWeight: "600",
  },

  safetyBanner: {
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: -4,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  safetyBannerBody: {
    flex: 1,
  },
  safetyBannerTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#1D4ED8",
  },
  safetyBannerText: {
    marginTop: 4,
    fontSize: 12,
    lineHeight: 18,
    color: "#475569",
  },

  inputBar: {
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 12,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 10,
  },
  input: {
    flex: 1,
    minHeight: 44,
    maxHeight: 100,
    backgroundColor: "#F3F4F6",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    color: "#111827",
  },
  inputDisabled: {
    color: "#94A3B8",
    backgroundColor: "#E5E7EB",
  },
  sendBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.BLUE,
    alignItems: "center",
    justifyContent: "center",
  },
  inputNotice: {
    marginTop: 6,
    marginHorizontal: 2,
    fontSize: 11,
    lineHeight: 16,
    color: "#6B7280",
  },
});
