import { StyleSheet } from "react-native";
import { COLORS } from "../../constants/colors";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#F8FAFC",
  },
  header: {
    height: 56,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    flex: 1,
    marginLeft: 8,
    fontSize: 18,
    fontWeight: "800",
    color: "#0F172A",
  },
  headerRight: {
    width: 36,
  },
  content: {
    padding: 16,
    paddingBottom: 28,
    gap: 16,
  },
  heroCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: "#0F172A",
  },
  heroBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  heroBadgeText: {
    color: "#DBEAFE",
    fontSize: 12,
    fontWeight: "700",
  },
  heroTitle: {
    marginTop: 12,
    color: "#FFFFFF",
    fontSize: 22,
    lineHeight: 30,
    fontWeight: "800",
  },
  heroText: {
    marginTop: 10,
    color: "#CBD5E1",
    fontSize: 14,
    lineHeight: 22,
  },
  sectionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
  },
  sectionSubtitle: {
    marginTop: 6,
    fontSize: 13,
    lineHeight: 20,
    color: "#64748B",
  },
  list: {
    marginTop: 12,
    gap: 10,
  },
  listRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  listDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    marginTop: 6,
    backgroundColor: COLORS.BLUE,
  },
  listText: {
    flex: 1,
    color: "#334155",
    fontSize: 13,
    lineHeight: 20,
  },
  actionBtn: {
    marginTop: 14,
    height: 46,
    borderRadius: 12,
    backgroundColor: COLORS.BLUE,
    alignItems: "center",
    justifyContent: "center",
  },
  actionBtnText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "800",
  },
  secondaryBtn: {
    marginTop: 10,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#EFF6FF",
    borderWidth: 1,
    borderColor: "#BFDBFE",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryBtnText: {
    color: COLORS.BLUE,
    fontSize: 14,
    fontWeight: "700",
  },
  contactRow: {
    marginTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  contactTextWrap: {
    flex: 1,
  },
  contactLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#64748B",
    textTransform: "uppercase",
  },
  contactValue: {
    marginTop: 2,
    fontSize: 14,
    color: "#0F172A",
    fontWeight: "600",
  },
  blockedRow: {
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#FFFFFF",
  },
  blockedName: {
    fontSize: 15,
    fontWeight: "800",
    color: "#111827",
  },
  blockedMeta: {
    marginTop: 6,
    fontSize: 12,
    lineHeight: 18,
    color: "#6B7280",
  },
  unblockBtn: {
    marginTop: 12,
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EEF2FF",
  },
  unblockBtnText: {
    color: "#3730A3",
    fontWeight: "700",
    fontSize: 13,
  },
  reportRow: {
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  reportTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
  },
  reportMeta: {
    marginTop: 6,
    fontSize: 12,
    lineHeight: 18,
    color: "#475569",
  },
  pendingTag: {
    marginTop: 10,
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#FEF3C7",
  },
  pendingTagText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#92400E",
  },
  emptyState: {
    marginTop: 12,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  emptyStateText: {
    color: "#64748B",
    fontSize: 13,
    lineHeight: 20,
  },
});

